-- DDL for EMPLOYEES Table
CREATE TABLE employees (employee_id   NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY                   
                       ,employee_name VARCHAR2(50) NOT NULL              
		       ,job_title     VARCHAR2(50) NOT NULL
		       ,manager_id    NUMBER(10)
		       ,date_hired    DATE         NOT NULL
		       ,salary        NUMBER(10)   NOT NULL
		       ,department_id NUMBER(5)    NOT NULL
		       );

ALTER TABLE employees ADD COMMENT ON TABLE employees IS 'This table holds the employee information';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.employee_id IS 'The unique identifier for the employee';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.employee_name IS 'The name of the employee';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.job_title IS 'The job role undertaken by the employee. Some employees may undertaken the same job role';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.manager_id IS 'Line manager of the employee';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.date_hired IS 'The date the employee was hired';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.salary IS 'Current salary of the employee';
ALTER TABLE employees ADD COMMENT ON COLUMN employees.department_id IS 'Each employee must belong to a department';

ALTER TABLE employees
ADD CONSTRAINT employees_pk PRIMARY KEY (employee_id);

ALTER TABLE employees 
ADD CONSTRAINT departments_fk FOREIGN KEY (department_id) REFERENCES departments(department_id);
/